---
- name: Copy files using sftp from remote servers
  hosts: awx
  vars:
    servers:
      - ip: "192.168.0.10"
        filename: "pruebasubuntu.txt"
      - ip: "192.168.0.12"
        filename: "pruebas2.txt"
      - ip: "192.168.0.11"
        filename: "pruebas.txt"
  tasks:
    - name: Copy file using sftp from remote servers
      expect:
        command: "sftp awx@{{ item.ip }}:/home/awx/{{ item.filename }} /home/awx/"
        responses:
          "awx@{{ item.ip }}'s password:": "1595"
      loop: "{{ servers }}"
      loop_control:
        loop_var: item